# -*- coding: utf-8 -*-
"""プロメンコピー

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gMscklaBVmQ7XDX0aI3vmQpYuyXlAPe8
"""

import streamlit as st
import pandas as pd
import requests
import mymodel as m

list_runsco = []
list_A=[]
list_B=[]
n = 0
i=0

list_kekka = ["得点", "ミス"]
list_syurui = ["DS", "BT", "SS", "PS", "NM", "7MT"]
list_iti = ["右", "左", "中"]
list_kosu = ["右上", "右下", "左上", "左下"]

st.title("スコア分析")

def nyuuryoku():
    global list_runsco, n, list_A, list_B,i
    unique_key_teamserect = f"teamserect_{len(list_runsco)}"
    unique_key_sebanngou = f"sebanngou_{len(list_runsco)}"
    unique_key_sokkou = f"sokkou_{len(list_runsco)}"
    unique_key_kekka = f"kekka_{len(list_runsco)}"
    unique_key_iti = f"iti_{len(list_runsco)}"
    unique_key_syurui = f"syurui_{len(list_runsco)}"
    unique_key_kosu = f"kosu_{len(list_runsco)}"
    unique_key_senntaku = f"senntaku_{len(list_runsco)}"

    teamserect = st.selectbox(label='どちらのチームに入力しますか？',
                      options=("A","B"),
                      key=unique_key_teamserect)

    sebanngou = st.number_input("背番号", 1, 100, 1, key=unique_key_sebanngou)

    sokkou = st.radio(label='速攻かどうか',
                      options=("FB", "QS", "なし"),
                      key=unique_key_sokkou)

    kekka = st.radio(label="結果を選択してください",
                           options=list_kekka,
                           key=unique_key_kekka)

    iti = st.selectbox(label="シュート位置を入力してください",
                         options=list_iti,key=unique_key_iti)

    syurui = st.selectbox(label="シュートの種類を選択してください",
                            options=list_syurui,key=unique_key_syurui)

    kosu = st.selectbox(label="コースを選択してください",
                          options=list_kosu,key=unique_key_kosu)

    senntaku = st.radio(label='入力を続けますか？',
                        options=("終了","続ける"),key=unique_key_senntaku)

    data = [teamserect,sebanngou, sokkou, kekka, iti, syurui, kosu]
    list_runsco.append(data)

    if list_runsco[i][0]=="A":
        list_A.append(list_runsco[i])

    if list_runsco[i][0]=="B":
        list_B.append(list_runsco[i])
    i=i+1

    if senntaku == "終了":
        n = 2
        st.write(list_runsco)
        st.write(list_A)
        st.write(list_B)

while n <1:
    nyuuryoku()